In [0]:
import pandas as pd
import numpy as np

In [0]:
dirty = pd.read_csv("dirty_data.csv")
clean = pd.read_csv("cleaned_data.csv")
test = pd.read_csv("test_data.csv")

for easy identification of nans and easy handling

In [0]:
clean = pd.DataFrame(np.where(clean.isna(),1,clean),columns=clean.columns)
dirty = pd.DataFrame(np.where(dirty.isna(),1,dirty), columns=clean.columns)
test =  pd.DataFrame(np.where(test.isna(),1,test),columns=clean.columns)
dirty_clean = pd.DataFrame(np.where(dirty.eq(clean),1,0),columns=clean.columns)

In [0]:
dirty_clean.drop("Rescue_ID",axis=1,inplace=True)

In [0]:
dirty_clean.head()

Date_Caught  Researcher  CaptureSite  ForagingGround  CaptureMethod  \
0            0           0            1               1              1   
1            1           0            0               0              1   
2            1           0            1               1              0   
3            1           0            1               1              0   
4            1           1            0               1              1   

   Fisher  LandingSite  Species  ReleaseSite  Tag_1  ...  CCW_cm  Weight_Kg  \
0       1            1        1            1      0  ...       0          1   
1       1            1        1            1      1  ...       0          1   
2       1            1        1            1      1  ...       1          1   
3       1            1        1            0      1  ...       0          1   
4       1            1        1            0      1  ...       1          1   

   Sex  TurtleCharacteristics  Status  Date_Release  Release_Admiss_Notes  \
0    1                      1       1             0                     1   
1    0                      1       1             1                     1   
2    0                      1       0             0                     1   
3    0                      0       0             0                     1   
4    0                      1       0             0                     1   

   SpecialRemarks  PCVNumber  Expenditure  
0               1          1            1  
1               1          1            1  
2               1          1            1  
3               1          1            1  
4               1          1            1  

[5 rows x 25 columns]

In [0]:
dirty.head()

Rescue_ID Date_Caught     Researcher   CaptureSite ForagingGround  \
0  1998_RE_0001   4/14/1998  researcher_12      site_110          creek   
1  1998_RE_0002    7/7/1998   researcher_4  not_recorded          ocean   
2  1998_RE_0003    8/3/1998              1       site_12          creek   
3  1998_RE_0004    8/7/1998  researcher_12      site_110          creek   
4  1998_RE_0005   9/25/1998  researcher_17  not_recorded          creek   

       CaptureMethod       Fisher   LandingSite    Species   ReleaseSite  ...  \
0                net   fisher_619       site_58  species_1       site_80  ...   
1           longline   fisher_522       site_22  species_1  not_recorded  ...   
2                net  fisher_1254  not_recorded  species_1      site_109  ...   
3                net   fisher_360  not_recorded  species_2      site_113  ...   
4  collected floater   fisher_865        site_8  species_3      site_109  ...   

  CCW_cm Weight_Kg      Sex      TurtleCharacteristics    Status Date_Release  \
0   58.5         1  Unknown                          1  Released    4/14/1998   
1     37         1        1                    1B-1LLS         1            1   
2     33         1        1                          1         1            1   
3   31.5         1        1                          1         1            1   
4   63.5         1        1  Bs on C+ old panga wounds         1            1   

         Release_Admiss_Notes SpecialRemarks PCVNumber Expenditure  
0                           1              1         1           1  
1                           1              1         1           1  
2                           1              1         1           1  
3                           1              1         1           1  
4  Found trapped in mangroves              1         1           1  

[5 rows x 26 columns]

In [0]:
clean.head()

Rescue_ID Date_Caught     Researcher CaptureSite ForagingGround  \
0  1998_RE_0001   4/17/1998  researcher_19    site_110          creek   
1  1998_RE_0002    7/7/1998  researcher_15     site_15          creek   
2  1998_RE_0003    8/3/1998   not_recorded     site_12          creek   
3  1998_RE_0004    8/7/1998  researcher_19    site_110          creek   
4  1998_RE_0005   9/25/1998  researcher_17      site_8          creek   

       CaptureMethod       Fisher   LandingSite    Species   ReleaseSite  ...  \
0                net   fisher_619       site_58  species_1       site_80  ...   
1           longline   fisher_522       site_22  species_1  not_recorded  ...   
2       not_recorded  fisher_1254  not_recorded  species_1      site_109  ...   
3       not_recorded   fisher_360  not_recorded  species_2      site_108  ...   
4  collected floater   fisher_865        site_8  species_3      site_121  ...   

  CCW_cm Weight_Kg      Sex            TurtleCharacteristics    Status  \
0  58.42         1  Unknown                                1  Released   
1  36.83         1  Unknown                          1B-1LLS         1   
2     33         1  Unknown                                1  Released   
3  31.75         1  Unknown  There was pillings on carapace.  Released   
4   63.5         1  Unknown        Bs on C+ old panga wounds  Released   

  Date_Release        Release_Admiss_Notes SpecialRemarks PCVNumber  \
0    4/17/1998                           1              1         1   
1            1                           1              1         1   
2     8/3/1998                           1              1         1   
3     8/7/1998                           1              1         1   
4    9/25/1998  Found trapped in mangroves              1         1   

  Expenditure  
0           1  
1           1  
2           1  
3           1  
4           1  

[5 rows x 26 columns]

In [0]:
clean_len = len(clean)
dirty_len = len(dirty)
test_len = len(test)

print("clean length",clean_len)
print("dirty length", dirty_len)
print("test length", test_len)

('clean length', 4292)
('dirty length', 4292)
('test length', 1362)


In [0]:
#concatenate clean, dirty and clean to get the unique value for each column
#this will make it possible to create a one hot encoding

all_data = pd.concat([clean,dirty,test],axis=0)

In [0]:
len(all_data)==(clean_len+dirty_len+test_len)

True

In [0]:
column = list(clean.columns)
del column[:2]

the main idea is to create an one hot encoding for each column, remember that each field in each column is the target variables,
so we do one hot encoding of the unique features

In [0]:
class_dummies = {}

for col in column:
    
    col_dummy = pd.get_dummies(all_data[col])
    
    class_dummies[col] = col_dummy

In [0]:
class_dummies[column[0]].head()

1  not_recorded  researcher_1  researcher_10  researcher_11  researcher_12  \
0  0             0             0              0              0              0   
1  0             0             0              0              0              0   
2  0             1             0              0              0              0   
3  0             0             0              0              0              0   
4  0             0             0              0              0              0   

   researcher_13  researcher_14  researcher_15  researcher_17  ...  \
0              0              0              0              0  ...   
1              0              0              1              0  ...   
2              0              0              0              0  ...   
3              0              0              0              0  ...   
4              0              0              0              1  ...   

   researcher_20  researcher_22  researcher_23  researcher_3  researcher_4  \
0              0              0              0             0             0   
1              0              0              0             0             0   
2              0              0              0             0             0   
3              0              0              0             0             0   
4              0              0              0             0             0   

   researcher_5  researcher_6  researcher_7  researcher_8  researcher_9  
0             0             0             0             0             0  
1             0             0             0             0             0  
2             0             0             0             0             0  
3             0             0             0             0             0  
4             0             0             0             0             0  

[5 rows x 23 columns]

In [0]:
train_columns ={}
test_columns = {}
i = 0

for col in column:
    
    train_columns[col] = class_dummies[col].iloc[clean_len:clean_len + dirty_len,:]
    test_columns[col] = class_dummies[col].iloc[clean_len + dirty_len:clean_len + dirty_len+test_len, :]

In [0]:
test_columns[column[1]].head()

not_recorded  site_10  site_102  site_103  site_104  site_105  site_106  \
0             0        0         0         0         0         0         0   
1             0        0         0         0         0         0         0   
2             0        0         0         0         0         0         0   
3             0        0         0         0         0         0         0   
4             0        0         0         0         0         0         0   

   site_107  site_108  site_110  ...  site_77  site_8  site_80  site_86  \
0         0         0         0  ...        0       0        0        0   
1         0         0         0  ...        0       0        0        0   
2         0         0         0  ...        0       0        0        0   
3         0         0         0  ...        0       0        0        0   
4         0         0         0  ...        0       0        0        0   

   site_87  site_90  site_91  site_92  site_93  site_98  
0        0        0        0        0        0        0  
1        0        0        0        0        0        0  
2        0        0        0        0        0        0  
3        0        0        0        0        0        0  
4        0        0        0        0        0        0  

[5 rows x 83 columns]

In [0]:
from lightgbm import LGBMClassifier

In [0]:
x_train = train_columns[column[0]]
y = dirty_clean[column[0]]
x_test = test_columns[column[0]]

In [0]:
model = LGBMClassifier()

In [0]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

In [0]:
x,x_val,y,y_val = train_test_split(x_train,y,test_size=0.1,shuffle=True,random_state=42)

In [0]:
model.fit(x.values,y)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='split', learning_rate=0.1, max_depth=-1,
        min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
        n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
        random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
        subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [0]:
mean_absolute_error(model.predict(x_val),y_val)

0.011627906976744186

In [0]:
list(model.predict_proba(x_test))

[array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.51230894, 0.48769106]),
 array([0.44333372, 0.55666628]),
 array([0.51230894, 0.48769106]),
 array([0.44333372, 0.55666628]),
 array([0.4433

In [0]:
model = LGBMClassifier()

In [0]:
y_pred = model.predict_proba(x_test.values)
y_pred

array([[0.01859943, 0.98140057],
       [0.01859943, 0.98140057],
       [0.01859943, 0.98140057],
       ...,
       [0.09085476, 0.90914524],
       [0.09085476, 0.90914524],
       [0.09085476, 0.90914524]])

In [0]:
submission = pd.DataFrame({"Rescue_ID":test['Rescue_ID'], "error":y_pred[:,1]})
submission.to_csv("submission.csv", index=False)

In [0]:
sub_example = pd.read_csv("submission_example.csv")
sub = pd.read_csv("submission.csv")

In [0]:
sub_example.shape

(1362, 2)

## I think this method work very well, but the issue is am predicting the actual value, and am ment to predict the error
so if ucan find a way to change model.predict from 0 and 1 to something that predict 0.23 to 0.95 the model will increase drastically 

In [0]:
pred = test.copy()
i = 0
kp_col = []
for col in column:
    print(col)
    x_train = train_columns[col]
    y = dirty_clean[col]
    x_test = test_columns[col]
    
    if len(x_train.columns) <2:
        kp_col.append(col)
        continue;
    
    x,x_val,y,y_val = train_test_split(x_train,y,test_size=0.1,shuffle=True,random_state=42)
    
    clf = model
    
    clf.fit(x.values,y.values)
    
    print("mse error", mean_absolute_error(clf.predict(x_val.values),y_val))
    
    pred[col] = clf.predict(x_test.values)
    
    i +=1
    
    

Researcher
('mse error', 0.011627906976744186)
CaptureSite
('mse error', 0.018604651162790697)
ForagingGround
('mse error', 0.044186046511627906)
CaptureMethod
('mse error', 0.027906976744186046)
Fisher
('mse error', 0.07209302325581396)
LandingSite
('mse error', 0.013953488372093023)
Species
('mse error', 0.004651162790697674)
ReleaseSite
('mse error', 0.027906976744186046)
Tag_1
('mse error', 0.004651162790697674)
Tag_2
('mse error', 0.002325581395348837)
Tag_3
Lost_Tags
('mse error', 0.002325581395348837)
T_Number
('mse error', 0.0)
CCL_cm
('mse error', 0.04883720930232558)
CCW_cm
('mse error', 0.08604651162790698)
Weight_Kg
('mse error', 0.0069767441860465115)
Sex
('mse error', 0.2534883720930233)
TurtleCharacteristics
('mse error', 0.1)
Status
('mse error', 0.29534883720930233)
Date_Release
('mse error', 0.17674418604651163)
Release_Admiss_Notes
('mse error', 0.0069767441860465115)
SpecialRemarks
('mse error', 0.0069767441860465115)
PCVNumber
Expenditure


In [0]:
column

['Researcher',
 'CaptureSite',
 'ForagingGround',
 'CaptureMethod',
 'Fisher',
 'LandingSite',
 'Species',
 'ReleaseSite',
 'Tag_1',
 'Tag_2',
 'Tag_3',
 'Lost_Tags',
 'T_Number',
 'CCL_cm',
 'CCW_cm',
 'Weight_Kg',
 'Sex',
 'TurtleCharacteristics',
 'Status',
 'Date_Release',
 'Release_Admiss_Notes',
 'SpecialRemarks',
 'PCVNumber',
 'Expenditure']

In [0]:
np.ones(len(pred),).astype("int")

array([1, 1, 1, ..., 1, 1, 1])

In [0]:
pred["Date_Caught"] = np.ones(len(pred),).astype("int")

In [0]:
pred

Rescue_ID  Date_Caught  Researcher  CaptureSite  ForagingGround  \
0     2011_RE_0001            1           1            1               1   
1     2011_RE_0002            1           1            1               1   
2     2011_RE_0003            1           1            1               1   
3     2011_RE_0004            1           1            1               1   
4     2011_RE_0005            1           1            1               1   
5     2011_RE_0006            1           1            1               1   
6     2011_RE_0007            1           1            1               1   
7     2011_RE_0008            1           1            1               1   
8     2011_RE_0009            1           1            1               1   
9     2011_RE_0010            1           1            1               1   
10    2011_RE_0011            1           1            1               1   
11    2011_RE_0012            1           1            1               1   
12    2011_RE_0013            1           1            1               1   
13    2011_RE_0014            1           1            1               1   
14    2011_RE_0015            1           1            1               1   
15    2011_RE_0016            1           1            1               1   
16    2011_RE_0017            1           1            1               1   
17    2011_RE_0018            1           1            1               1   
18    2011_RE_0019            1           1            1               1   
19    2011_RE_0020            1           1            1               1   
20    2011_RE_0021            1           1            1               1   
21    2011_RE_0022            1           1            1               1   
22    2011_RE_0023            1           1            1               1   
23    2011_RE_0024            1           1            1               1   
24    2011_RE_0025            1           1            1               1   
25    2011_RE_0026            1           1            1               1   
26    2011_RE_0027            1           1            1               1   
27    2011_RE_0028            1           1            1               1   
28    2011_RE_0029            1           1            1               1   
29    2011_RE_0030            1           1            1               1   
...            ...          ...         ...          ...             ...   
1332  2011_RE_1336            1           1            1               1   
1333  2011_RE_1337            1           1            1               1   
1334  2011_RE_1338            1           1            1               1   
1335  2011_RE_1339            1           1            1               1   
1336  2011_RE_1340            1           1            1               1   
1337  2011_RE_1341            1           1            1               1   
1338  2011_RE_1342            1           1            1               1   
1339  2011_RE_1343            1           1            1               1   
1340  2011_RE_1344            1           1            1               1   
1341  2011_RE_1345            1           1            1               1   
1342  2011_RE_1346            1           1            1               1   
1343  2011_RE_1347            1           1            1               1   
1344  2011_RE_1348            1           1            1               1   
1345  2011_RE_1349            1           1            1               1   
1346  2011_RE_1350            1           1            1               1   
1347  2011_RE_1351            1           1            1               1   
1348  2011_RE_1352            1           1            1               1   
1349  2011_RE_1353            1           1            1               1   
1350  2011_RE_1354            1           1            1               1   
1351  2011_RE_1355            1           1            1               1   
1352  2011_RE_1356            1           1            1 

In [0]:
len(pd.read_csv("submission_example.csv"))

34050

In [0]:
pred.to_csv("pred.csv",index=False)

In [0]:
preds = pd.DataFrame()


nm = []
bm = []
for i,rescue in enumerate(pred["Rescue_ID"]):
    
    for i,col in enumerate(list(pred.columns[1:])):
        
        nm.append(rescue + " x "+ col)
        bm.append(pred.iloc[i,i+1])
    

In [0]:
preds["ID"] = nm
preds["error"] = bm

In [0]:
preds

ID  error
0                2011_RE_0001 x Date_Caught      1
1                 2011_RE_0001 x Researcher      1
2                2011_RE_0001 x CaptureSite      1
3             2011_RE_0001 x ForagingGround      1
4              2011_RE_0001 x CaptureMethod      1
5                     2011_RE_0001 x Fisher      1
6                2011_RE_0001 x LandingSite      1
7                    2011_RE_0001 x Species      1
8                2011_RE_0001 x ReleaseSite      1
9                      2011_RE_0001 x Tag_1      1
10                     2011_RE_0001 x Tag_2      1
11                     2011_RE_0001 x Tag_3      1
12                 2011_RE_0001 x Lost_Tags      1
13                  2011_RE_0001 x T_Number      1
14                    2011_RE_0001 x CCL_cm      1
15                    2011_RE_0001 x CCW_cm      1
16                 2011_RE_0001 x Weight_Kg      1
17                       2011_RE_0001 x Sex      0
18     2011_RE_0001 x TurtleCharacteristics      1
19                    2011_RE_0001 x Status      0
20              2011_RE_0001 x Date_Release      1
21      2011_RE_0001 x Release_Admiss_Notes      1
22            2011_RE_0001 x SpecialRemarks      1
23                 2011_RE_0001 x PCVNumber      1
24               2011_RE_0001 x Expenditure      1
25               2011_RE_0002 x Date_Caught      1
26                2011_RE_0002 x Researcher      1
27               2011_RE_0002 x CaptureSite      1
28            2011_RE_0002 x ForagingGround      1
29             2011_RE_0002 x CaptureMethod      1
...                                     ...    ...
34020           2011_RE_1364 x Date_Release      1
34021   2011_RE_1364 x Release_Admiss_Notes      1
34022         2011_RE_1364 x SpecialRemarks      1
34023              2011_RE_1364 x PCVNumber      1
34024            2011_RE_1364 x Expenditure      1
34025            2011_RE_1365 x Date_Caught      1
34026             2011_RE_1365 x Researcher      1
34027            2011_RE_1365 x CaptureSite      1
34028         2011_RE_1365 x ForagingGround      1
34029          2011_RE_1365 x CaptureMethod      1
34030                 2011_RE_1365 x Fisher      1
34031            2011_RE_1365 x LandingSite      1
34032                2011_RE_1365 x Species      1
34033            2011_RE_1365 x ReleaseSite      1
34034                  2011_RE_1365 x Tag_1      1
34035                  2011_RE_1365 x Tag_2      1
34036                  2011_RE_1365 x Tag_3      1
34037              2011_RE_1365 x Lost_Tags      1
34038               2011_RE_1365 x T_Number      1
34039                 2011_RE_1365 x CCL_cm      1
34040                 2011_RE_1365 x CCW_cm      1
34041              2011_RE_1365 x Weight_Kg      1
34042                    2011_RE_1365 x Sex      0
34043  2011_RE_1365 x TurtleCharacteristics      1
34044                 2011_RE_1365 x Status      0
34045           2011_RE_1365 x Date_Release      1
34046   2011_RE_1365 x Release_Admiss_Notes      1
34047         2011_RE_1365 x SpecialRemarks      1
34048              2011_RE_1365 x PCVNumber      1
34049            2011_RE_1365 x Expenditure      1

[34050 rows x 2 columns]

In [0]:
preds.to_csv("submit.csv",index=False)